apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-client
  template:
    metadata:
      labels:
        app: ms-client
    spec:
      containers:
      - name: ms-client-container
        image: felipepxavier/api-ms-client:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ms-client-config
        - secretRef:
            name: ms-client-secrets
