name: Run API Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      NODE_ENV: test
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
      API_URL: http://localhost
      API_PORT: 3000
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Print Environment Variables
        run: |
            echo "DB_HOST: $DB_HOST"
            echo "DB_PORT: $DB_PORT"
            echo "DB_NAME: $DB_NAME"
            echo "DB_USER: $DB_USER"
            echo "DB_PASSWORD: $DB_PASSWORD"
            echo "API_URL: $API_URL"
            echo "API_PORT: $API_PORT"

      - name: Check PostgreSQL Status
        run: |
              CONTAINER_NAME=$(docker ps --filter "ancestor=postgres:15" --format "{{.Names}}")
              docker logs $CONTAINER_NAME


      - name: Wait for PostgreSQL to be ready
        run: |
              timeout 20s bash -c 'until pg_isready -h 127.0.0.1 -U $DB_USER -d $DB_NAME; do sleep 1; done'
    
      - name: Create Database (if needed)
        run: |
              PGPASSWORD=$DB_PASSWORD psql -h 127.0.0.1 -U $DB_USER -c "CREATE DATABASE $DB_NAME;"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Start API and Run Tests
        run: |
          timeout 20s bash -c 'until pg_isready -U $DB_USER -d $DB_NAME; do sleep 1; done'

          yarn dev &

          sleep 5 

          yarn test
